config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'home/raise_zombie'
  resources :blogs
  resources :grunts
  resources :zombies
  resources :graveyards
end

app/models/grunt.rb
class Grunt < ActiveRecord::Base
  include Commentable
  has_many :comments, as: :commentable, dependent: :delete_all
  belongs_to :zombie

  paginates_per 25
  max_paginates_per 100
end

app/controllers/grunts_controller.rb
class GruntsController < ApplicationController
  before_action :set_grunt, only: [:show, :edit, :update, :destroy]

  # GET /grunts
  # GET /grunts.json
  def index
    @grunts = Grunt.all.page(params[:page])
  end

  # GET /grunts/1
  # GET /grunts/1.json
  def show
  end

  # GET /grunts/new
  def new
    @grunt = Grunt.new
  end

  # GET /grunts/1/edit
  def edit
  end

  # POST /grunts
  # POST /grunts.json
  def create
    @grunt = Grunt.new(grunt_params)

    respond_to do |format|
      if @grunt.save
        format.html { redirect_to @grunt, notice: 'Grunt was successfully created.' }
        format.json { render :show, status: :created, location: @grunt }
      else
        format.html { render :new }
        format.json { render json: @grunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grunts/1
  # PATCH/PUT /grunts/1.json
  def update
    respond_to do |format|
      if @grunt.update(grunt_params)
        format.html { redirect_to @grunt, notice: 'Grunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @grunt }
      else
        format.html { render :edit }
        format.json { render json: @grunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grunts/1
  # DELETE /grunts/1.json
  def destroy
    @grunt.destroy
    respond_to do |format|
      format.html { redirect_to grunts_url, notice: 'Grunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grunt
      @grunt = Grunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grunt_params
      params.require(:grunt).permit(:message, :zombie_id)
    end
end

app/helpers/grunts_helper.rb
module GruntsHelper
end

app/views/grunts/_form.html.erb
<%= form_for(@grunt) do |f| %>
  <% if @grunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grunt.errors.count, "error") %> prohibited this grunt from being saved:</h2>

      <ul>
      <% @grunt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :zombie_id %><br>
    <%= f.collection_select :zombie_id, Zombie.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grunts/edit.html.erb
<h1>Editing Grunt</h1>

<%= render 'form' %>

<%= link_to 'Show', @grunt %> |
<%= link_to 'Back', grunts_path %>

app/views/grunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grunts</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Message</th>
      <th>Zombie</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @grunts.each do |grunt| %>
      <tr>
        <td><%= grunt.message %></td>
        <td><%= grunt.zombie.name %></td>
        <td>
					<div class="btn-group">
						<%= link_to 'Show', grunt, class: 'btn btn-xs btn-success' %>
        		<%= link_to 'Edit', edit_grunt_path(grunt), class: 'btn btn-xs btn-warning' %>
        		<%= link_to 'Destroy', grunt, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
					</div>
				</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row">
	<%= page_entries_info @grunts %>
</div>
<div class="row">
	<%= paginate @grunts %>
</div>
<div class="row">
	<%= link_to 'New Grunt', new_grunt_path, class: 'btn btn-primary' %>
</div>

app/views/grunts/new.html.erb
<h1>New Grunt</h1>

<%= render 'form' %>

<%= link_to 'Back', grunts_path %>

app/views/grunts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h3><small><%= @grunt.zombie.name %> says: </small><%= @grunt.message %></h3>
  <%= link_to 'Edit', edit_grunt_path(@grunt), class: 'btn btn-primary btn-sm' %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Posted</th>
      <th>Zombie</th>
      <th>Message</th>
    </tr>
  </thead>

  <tbody>
    <% @grunt.comments.each do |comment| %>
      <tr>
        <td><%= comment.created_at.to_s('%B %d, %Y %l:%M %p') %></td>
        <td><%= link_to comment.zombie.name, comment.zombie %></td>
        <td><%= comment.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>