config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'home/raise_zombie'
  resources :blogs
  resources :grunts
  resources :zombies
  resources :graveyards
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @grunts = Grunt.includes(:zombie, :comments).order(created_at: :desc).limit(10)
    @blogs = Blog.order(created_at: :desc).limit(10)
  end

  def raise_zombie
    ZombieRaiser.new.raise_zombie
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-9 pull-right">
    <%= link_to 'Raise', home_raise_zombie_path, class: 'btn btn-danger' %>
  </div>
</div>

<h1>Recent Grunts</h1>

<% @grunts.each do |grunt| %>
  <div class="page-header">
    <h3><small><%= grunt.zombie.name %> says: </small><%= grunt.message %> <span class="badge"><%= grunt.comments.size %></span></h3>
  </div>
  <div class="btn-group">
    <%= link_to 'Show', grunt, class: 'btn btn-xs btn-success' %>
    <%= link_to 'Edit', edit_grunt_path(grunt), class: 'btn btn-xs btn-warning' %>
    <%= link_to 'Destroy', grunt, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
  </div>
  <hr>
<% end %>

<h1>Recent Blogs</h1>

<% @blogs.each do |blog| %>
  <blockquote>
    <p><%= blog.body.truncate_words(20) %></p>
    <footer><%= blog.title %> by <cite><%= blog.zombie.name %></cite> <span class="badge"><%= blog.comments.size %></span></footer>
  </blockquote>
  <div class="btn-group">
    <%= link_to 'Show', blog, class: 'btn btn-xs btn-success' %>
    <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-xs btn-warning' %>
    <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
  </div>
  <hr>
<% end %>